fix: Symbolic application icons
pop-os/icon-theme pull request #59
Opened 2020-01-13 19:27 UTC by isantop

We previously were lacking symbolic versions of our icons for some applications. Most of the applications now contain both symbolic and hicolor icons, or the GNOME-provided icons match our designs anyway.

Fixes #27

2020-01-15 21:57 UTC, jackpot51 submitted a review, later dismissed

2020-01-16 16:00 UTC, brs17 requested changes
This seems to have fixed most icons but not all of them(after testing all applications that come with Pop!_OS by default).

Do not match our icon:
![archive](https://user-images.githubusercontent.com/7460774/72539003-e84fef00-383b-11ea-9959-8e6cef4a20e1.jpg)
![charmap](https://user-images.githubusercontent.com/7460774/72539005-e8e88580-383b-11ea-8fa1-8aadd8d600ee.jpg)
![fonts](https://user-images.githubusercontent.com/7460774/72539006-e8e88580-383b-11ea-85cc-11a62a3fec0d.jpg)
![help](https://user-images.githubusercontent.com/7460774/72539009-e8e88580-383b-11ea-8968-6f9d59079e74.jpg)
![powerstats](https://user-images.githubusercontent.com/7460774/72539011-e9811c00-383b-11ea-9d13-8e386715243a.jpg)
![settings](https://user-images.githubusercontent.com/7460774/72539013-e9811c00-383b-11ea-8d4a-6049913ccef6.jpg)
![terminal](https://user-images.githubusercontent.com/7460774/72539014-e9811c00-383b-11ea-81e0-0039bea7741c.jpg)

Looks more like our icon but still a tad different (note the placement of `+ x / =` )
![calc](https://user-images.githubusercontent.com/7460774/72539004-e8e88580-383b-11ea-8b1f-75a5c6aec693.jpg)

Nice creative touch!
![gedit](https://user-images.githubusercontent.com/7460774/72539007-e8e88580-383b-11ea-80a4-523cc81c6ef0.jpg)

2020-01-17 21:39 UTC, jackpot51 approved these changes

2020-01-28 22:15 UTC, brs17 approved these changes

2020-01-29 22:00 UTC, merged